//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gadara
{
    using System;
    using System.Collections.Generic;
    
    public partial class Task
    {
        public int T_id { get; set; }
        public string T_title { get; set; }
        public string T_desc { get; set; }
        public string T_status { get; set; }
        public Nullable<System.DateTime> T_duedata { get; set; }
        public Nullable<int> U_id { get; set; }
    
        public virtual User User { get; set; }
    }
}
